name: CI/CD - FastAPI Microservice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      IMAGE_TAG: latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Run tests
      - name: Run tests
        run: |
          PYTHONPATH=. pytest

          - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ***
        
      - name: Verify AWS Identity
        run: aws sts get-caller-identity
      
      - name: Update kubeconfig with role-arn
        run: |
          aws eks update-kubeconfig \
            --region *** \
            --name *** \
            --alias github-actions-context
          
          # Clear any cached credentials
          rm -rf ~/.kube/cache
      
      - name: Wait for auth to propagate
        run: sleep 5
      
      - name: Test cluster access
        run: |
          kubectl get nodes
          kubectl auth can-i create deployment

      # 6️⃣ Login to ECR
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      

      # 7️⃣ Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update kubeconfig and deploy
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }} \
            --alias github-actions-context
      
          # Verify access
          kubectl config use-context github-actions-context
          kubectl get nodes
          kubectl auth can-i create deployment
      
          # Deploy manifests
          kubectl apply -f k8s/
        
